### ISSUE TITLE
We need to update the footer

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1405] opened 2024-04-11 13:37 UTC
Debra sent us the following request:

> Hi Developers,
> Following our meeting in Halifax and the discussion about the footer and the acknowledgements, I have drafted up a possible version of the footer. See "mock up" document, attached.
> 
> Also, here is the link to images of all the logos: `(there was a link here; all the images within the folder are attached below)`

I will open another issue for the Acknowledgements page.

## Mockup:
![Screenshot 2024-04-11 at 9 31 14 AM](https://github.com/DDMAL/CantusDB/assets/58090591/c7f687cf-174e-470b-bb7a-9f574d43333c)

## Logos:
![image](https://github.com/DDMAL/CantusDB/assets/58090591/5190efe1-d0c6-4902-ba83-68083a86090b)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/5e88c6f3-cfdc-4111-88a4-a8f5df6d0a6a)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/91ee646f-d551-4ec5-985d-826fa34ab1f9)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/814d9768-1bed-4450-aac5-1c67a4f0e733)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/bbcfa06c-45a6-41e9-9d75-48e325e3de3b)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/39f9e919-cbfb-40ed-b5db-bd09c8f9d835)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/20713c58-2c3c-4167-938f-265f4e4bf01a)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/1dc4d27f-c4e7-4ab3-905c-4796141a0414)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/7a831df2-d82d-48dd-9729-371ca1575f65)

## (Legacy Logos)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/1eeecd86-03e9-4de5-ae7b-9058ea9b4c11)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/0f1b7845-5138-4290-bec3-37ea78fbe9d9)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/178c29b7-3b09-4824-9ed1-5dc5770c49a1)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/6cae500c-d20f-4463-a1b6-bf7259c2a2f2)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/8d9161b2-45fe-4678-b7f7-fb3b3dbaf27d)
![image](https://github.com/DDMAL/CantusDB/assets/58090591/90db44ef-ae5b-4d1b-aeea-14ed2632677f)

**Comment by annamorphism** [comment] 2024-04-11 14:38
Is there another logo for (what I assume is) Catholic U that includes the institution name? this one is a little mysterious...
EDIT: I see reading #1406 that the name will be incorporated elsewhere, so I guess it's fine.

As for the mock up, I have a few questions to confirm about the appearance: 
-ACENET is in the images but not in the text describing the images. Might be good to confirm where it should go. 
-Do we want all the logos about the centre (producing a sort of heart-shape), or justified at the edges (like the current rectangle)?
-The mock-up has the log-in button tucked in amongst the logos, where now it is separated off. Is this by design?

**Comment by jacobdgm** [comment] 2024-04-11 15:01
> -ACENET is in the images but not in the text describing the images. Might be good to confirm where it should go.

Good call. I've sent Debra an email asking for clarification, and included you as a recipient.

> -Do we want all the logos about the centre (producing a sort of heart-shape), or justified at the edges (like the current rectangle)?
> -The mock-up has the log-in button tucked in amongst the logos, where now it is separated off. Is this by design?

I think this is up to us to decide how to best set this up - it will need to be responsive to fit different screen sizes, at the very least. The log-in button is replaced by several links once a user is logged-in - a link to log out, a link to reset the password, and so on, as well as a bunch of admin-only navigation for sufficiently privileged people. I'm interpreting the mockup as an indication of which logos, and which versions of them, should be included, and in approximately which order. I think us developers need to come up with an implementation and then show it to Debra for her approval.

**Comment by jacobdgm** [comment] 2024-04-11 15:02
> Is there another logo for (what I assume is) Catholic U that includes the institution name? this one is a little mysterious...

The Catholic U logo seems to be designed for display on a dark background - the text is in white, while the background is transparent.

**Comment by jacobdgm** [comment] 2024-04-16 13:01
> -ACENET is in the images but not in the text describing the images. Might be good to confirm where it should go.

Debra has responded about this, it seems that the logo appears in the mockup where it should be, but that Debra accidentally left it out of the list of acronyms just above it. So the ACENET logo should be included.

**Comment by dchiller** [comment] 2024-05-27 12:36
From Debra, we also want to change what is under the "Cantus Team" header in the footer (lol) to be:

Debra Lacoste | Project Manager
Jennifer Bain | Principal Investigator
Development and Maintenance (link to the DDMAL lab)

**Closed as completed** 2024-05-29 13:08 UTC
Labels: priority: high, special debra request
