### ISSUE TITLE
For chants inherited from OldCantus with no source, should we assign them to a dummy "Unknown Source" source?

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#996] opened 2023-08-17 18:19 UTC
...and yet there exists https://cantusdatabase.org/chant/1001628 (see also https://cantusdatabase.org/admin/main_app/chant/1001628/change/) - no source, and must have been created in NewCantus since its ID is greater than 1000000...

**Comment by annamorphism** [comment] 2023-08-17 18:35
Interesting, because from the admin page you can see it was intended to be the chant "Bone pastor" on 12r of GB-Lbl Add 23935, which the user successfully created at https://cantusdatabase.org/chant/1001624 . Did they delete a duplicate and somehow this created a source-less chant?

**Comment by jacobdgm** [comment] 2023-08-17 19:20
Something weird happened when this chant was created:
```python
>>> sourceless = Chant.objects.get(id=1001628)
>>> sourceless
<Chant: "Bone pastor panis vere" (1001628)>
>>> sourceless.date_created
datetime.datetime(2023, 8, 9, 23, 1, 21, 887332, tzinfo=datetime.timezone.utc)
>>> sourceless.date_updated
datetime.datetime(2023, 8, 9, 23, 1, 21, 887362, tzinfo=datetime.timezone.utc) # this is a few milliseconds after it was created - the object was created, and it hasn't been touched since
>>> sourceless.created_by # notice there is no created_by
>>> sourceless.last_updated_by # ...and yet it was updated by someone
<User: Paul Howard>
```

**Comment by jacobdgm** [comment] 2023-08-17 19:22
Also, note that the successfully-created chant, 1001624, has a lower ID than 1001628, so the faulty chant was created after the working version of the chant.

**Comment by annamorphism** [comment] 2023-08-17 19:41
I noticed that too. Is it possible that, say, the request to create the chant was made twice (with the second being somehow pathological--maybe the request was interrupted?)

**Comment by annamorphism** [comment] 2023-08-18 00:56
I'm still mystified. I tried doing various things like hitting the back button while a chant was uploading, creating two chants in separate tabs, etc., but while I can get there to be conflicting success and error messages (see below--one even suggests I made a different chant than I did) I haven't managed to create a sourceless object.

![image](https://github.com/DDMAL/CantusDB/assets/67451875/93c81fd7-366c-4566-8ddd-52a0c13d89ec)
![image](https://github.com/DDMAL/CantusDB/assets/67451875/b86474f0-9147-44a7-ba84-8b6fe8e4fd43)


From the time stamps, I can see this particular user made a bunch of chants, then had about a fifteen minute break before creating this weird thing and touching up a few previous ones and stopping for the day--which makes me wonder if either there was some sort of timeout interruption or perhaps a closing of the laptop mid-chant or what.

**Comment by annamorphism** [comment] 2023-08-18 20:46
I have emailed the user in question just to see if he remembers anything. 

Meanwhile I have discovered that if you interrupt during a save (e.g. by turning off the internet), and then save again, I can consistently get the message that my chant was created (as indeed it is, by checking on the content-overview), but also that that the sequence/folio combination already exists in the source (and the create page shows up again with the same entries, as if the action had failed.) I am guessing that the notification about the second (failed) attempt reaches me before the one about the first (successful) event, hence the combined success/failure message. I am wondering if, if I blipped the internet at juuuuust the right moment, I would actually interrupt the first request during the check for its source.

**Comment by jacobdgm** [comment] 2023-08-21 13:21
When a user sends a POST request to create a new object, I'm pretty sure Django either receives the entire request or it doesn't, and then it creates an object IFF it received an entire, valid request (i.e. the beginning of a request, with the last part cut off, would not be a valid request).

That said, this is really useful information, and will certainly help in debugging! The duplicate, conflicting messages are intriguing.

**Comment by annamorphism** [comment] 2023-08-21 17:12
I will note one can create a sourceless chant in the admin panel (https://cantusdatabase.org/admin/main_app/chant/1002215/change/). Obviously that's not how this particular one was created, but it means there is some sort of (deliberate?) loophole for this to happen.
Possibly of interest: this newly-created chant has an incipit in the admin panel that also shows up in content overview. 
<img width="1102" alt="image" src="https://github.com/DDMAL/CantusDB/assets/67451875/0c725875-703d-4366-9b96-ada74bcd132c">
But for our initial problem chant, the Overview shows it as "Chant Object" --it apparently has no incipit. Hmm. 
ETA: it also has no name in the "updated by" (ordinarily this is the same as the name in the creator field)--this is similar to our original problem chant, but the other way around.

**Comment by annamorphism** [comment] 2023-08-21 17:22
Some other fun errors I can cause:

If I use the "fulltext editor" (as opposed to the edit tab on a chant view), I can change a chant to have the same sequence/folio number as another existing chant. Instead of an error message to revisit the form,  I will get a 500 error, but the duplicate chant does end up being created. 
If in doing this I remove the last remaining chant on some folio, I get a 404 message, but it still creates the new chant. 
Still looking for how it gets the source and incipit dropped but we seem to be warmer...

**Comment by annamorphism** [comment] 2023-08-21 18:57
From the user in question: 

"Thinking back, I do have a conjecture about how this may have happened. I recall that when I began entering folio 11v, I used a two digit code for the folio number. As I'd only worked on folios in the hundreds, I hadn't considered the importance of the three digit code for sorting. So, after logging a number of chants I noticed that the "select a page" dropdown menu wasn't showing the most recent folio I had logged and I soon realized that the system sorted "11v" as following "110v" (or something of the sort). Backtracking, I changed the folio numbers I'd already logged to "011v." I seem to remember that when I changed the last chant, thus erasing "11v" entirely from the system, I received an error message. However, I checked the database and this final chant had indeed been successfully edited, so I thought the error message inconsequential. Turns out I must have been wrong! ""

I've tried doing similar things to what is described here--editing chants to have other folio numbers and/or subsequently deleting them--and while it did allow me to find the errors upthread, I haven't reproduced the "Chant Object" yet.

**Comment by ahankinson** [comment] 2023-08-22 08:03
From what I can see you have `null=True` and `blank=True` on the source relationship in your model. This marks the Source as optional.

If you want to make it required at the data level, remove those. Then it will be an error when a chant is saved without a source record.

**Comment by lucasmarchd01** [comment] 2023-08-22 15:12
Thanks @annamorphism and @ahankinson for the information. Removing `null=True` and `blank=True` should ensure that any chant/sequence without a valid source will be flagged as an error during the data validation process in the future. Once we remove these flags and perform the data migration, our existing chants without sources will likely result in an IntegrityError, so I assume we should make sure all of these chants/sequences are dealt with before making this change unless there is a better way of doing it.

**Comment by lucasmarchd01** [comment] 2023-08-22 21:28
A few options:
- Provide a default source for objects that do not have one until someone can go and update them manually.
- Update existing records with valid values before migrating
- Remove objects that cannot be updated to comply with the new constraints.

**Comment by annamorphism** [comment] 2023-08-22 21:46
I kind of like the idea of providing a default source (called, say,"Source Unknown") for these weird objects--it means a shorter wait than option 2, and it will make them a lot easier to find and update in the future.

**Comment by lucasmarchd01** [comment] 2023-08-23 13:50
@annamorphism Okay, this makes the most sense. I think it's logical to do this with the sourceless chants, but for sequences I hesitate to create a default source since we don't already have dummy or test sources in the Calvin Bower sequence database. How should we handle the sourceless sequences?

**Comment by lucasmarchd01** [comment] 2023-08-23 13:56
The sequences can still be set to belong to the same default source as the chants, we will just have a mix of chants and sequences in that source. Only the chants will be visible on the site when viewing the source inventory but the sequences can all still be found and handled in the taxonomy manager.

**Comment by annamorphism** [comment] 2023-08-23 15:06
Sure. I think I'm OK with the Bower database having a mystery source as well--it may not have dummy sources, but it has other things that need cleaning up (like the titles of the various "Notes" fields) so I don't think it would be harmful to add it, and would likely be helpful. 
Question:  currently some of the chants have no source, but do have some sort of associated RISM siglum. If we attach them to a dummy source, will this be replaced by a dummy siglum?

**Comment by lucasmarchd01** [comment] 2023-08-23 18:44
If we attach these chants in the dummy source, their RISM siglum and any other data (other than the source) will remain the same.

**Comment by lucasmarchd01** [comment] 2023-08-24 14:19
The dummy sources have now been created here ([Unknown Source (Chants)](https://cantusdatabase.org/source/1000003)) and here ([Unknown Source (Sequences)](https://cantusdatabase.org/source/1000004))

**Comment by jacobdgm** [comment] 2023-08-29 13:48
I assume Debra has been consulted about and has approved the Unknown Source sources idea?

**Comment by lucasmarchd01** [comment] 2023-08-29 14:16
> I assume Debra has been consulted about and has approved the Unknown Source sources idea?

I'll reach out to Debra to ask about this, I assumed it would be okay with Anna's approval. If Debra has an issue with this it should be easy to unassign them from these sources.

**Comment by annamorphism** [comment] 2023-08-29 15:18
just FYI Debra is off-grid this week (I'm her delegate for "Cantus emergencies") so you won't get a response from her directly for a few days.

**Comment by jacobdgm** [comment] 2023-09-08 19:45
This issue, as it was originally named, has been solved. I'm assuming it hasn't yet been closed because we're waiting for confirmation from Debra about the "Unknown Source" source idea we implemented. Renaming the issue to reflect this.

**Closed as completed** 2023-09-22 15:20 UTC
Labels: priority: high
