### ISSUE TITLE
CSV export erroneously uses chants' sigla, rather than the chants' source's siglum

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#1379] opened 2024-03-19 20:37 UTC
This is a stub; at some point I (or someone else) will get around to copying relevant discussion from the email chain into this issue.

I will note that I thought we had addressed every situation where we were using chants' sigla. Evidently we missed one; we should do a thorough search through the code to make sure there are no other places where we're displaying these values we shouldn't be displaying.

**Comment by dchiller** [comment] 2024-03-22 12:02
Closing as duplicate of #1365

**Closed as completed by dchiller** 2024-03-22 12:02 UTC
Labels: bug, duplicate, priority: medium, simple fix
