### ISSUE TITLE
feature request: upload CSV

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/CantusDB#1099] opened 2023-10-21 17:41 UTC
Discussion today revealed that @kyrieb-ekat and I (and Debra) have Cantus-ish things that would be nice to import and turn into an index. @jacobdgm indicated this would be a doable thing to make. We'd need to think about implementation
-Probably this should be accessible for only admins? It could even be only for developers, but we don't want to create work cleaning up CSV files if that time could be better spent elsewhere. Probably we don't want this to be accessible for lower-level editors. 
-We would want to make sure that the CSV files are in the right format. Not sure how to ensure this--tbd.

**Comment by dchiller** [comment] 2024-10-25 19:16
Closing as duplicate of #1259.

**Closed as completed by dchiller** 2024-10-25 19:16 UTC
Labels: enhancement, priority: medium, special debra request
