### ISSUE TITLE
We should remove the extra line in each row of `searchms` results

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#852] opened 2023-07-17 13:42 UTC
Poking around OldCantus for CU-related things, I just found a feature I had never seen before but that is not implemented in NewCantus. If this is a known difference, close the issue....

The results on a `searchms` page have a details button that accordions out to include some chant information.

OldCantus: https://cantus.uwaterloo.ca/searchms/123723?name=&genre=All&mode=&feast=&cid=&volpiano=All&combine_op=starts&t=dominus+defensor&field_indexing_notes_value_op=contains&field_indexing_notes_value=
![image](https://github.com/DDMAL/CantusDB/assets/11023634/cbe4d6b7-49eb-4767-96d4-a40c2e8a8130)

NewCantus: http://206.12.88.113/searchms/123723?op=starts_with&keyword=dominus+defensor&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=
![image](https://github.com/DDMAL/CantusDB/assets/11023634/a115ca72-5039-41df-ace8-110c734a2561)

**Comment by jacobdgm** [comment] 2023-07-18 19:38
I'm guessing this has to do with the Indexing Notes search field, so that you can look at the indexing notes for chants without opening the chants in new pages.

@annamorphism, do you think this is necessary to include?

**Comment by annamorphism** [comment] 2023-07-19 08:03
It's not exactly that--it's also hiding the full text unless you open "detail", for example. This table gives
Source-folio-sequence-incipit-feast-position-office-genre-ID-mode-differentia-imagelink, sort of like the "view full index" table but in a slightly different order. ("Source" seems redundant in this case but, ok.) Then "details" gives both full texts, volpiano, and indexing notes. 

NewCantus's version fixes the column widths, and includes the text right away.
So...Hmm.  The details thing is actually kind of clever in being space efficient AND keeping you on the page for all the necessary things BUT it also only exists for searchms, so I have rarely made use of it and don't have strong feelings about it. Ask Debra if this is something she specifically requested or if it was an experiment not to bother repeating.

**Comment by jacobdgm** [comment] 2023-07-20 13:32
Some discussion occurred over email:

Debra:
> I don't use that "Details" button, and I don't know who else does. I don't see a need for it, since you can click on the incipit and get to the actual record.
> 
> It may have been that someone wanted to compare two records on the same screen with the manuscript spelling field (?) but I believe there are other ways to do that with multiple windows.
> 
> If someone else in this email thread can think of a reason to keep the "Details" button, please mention it. Otherwise, I would tell you to NOT spend any time working on this task. We can spend your programming time in other ways.

Ich:
> Given Debra’s response, I suggest (and noted by Anna) that you remove the second row and the third (blank) row of each entry, so that at the full screen width each entry takes up only one row (as in OldCantus).

One thing is that the second row in the "Incipit" column (below the main link) is not just a duplicate of the first line - the first line is the incipit, while the second line is the full text (which you can see when you use a different search term: http://206.12.88.113/searchms/123723?op=starts_with&keyword=dominus&office=&genre=&cantus_id=&mode=&feast=&position=&melodies=)

In the end: it sounds like Debra doesn't want us to spend time implementing this. Going to mark this as low priority; eventually, we can figure out why Django is adding what looks like an extra line under the full text and figure out how to remove it. But this is cosmetic, and not at all urgent.

**Closed as completed** 2023-08-02 15:55 UTC
Labels: priority: low, cosmetic/accessibility
