### ISSUE TITLE
Unpublished sources showing in list with published sources

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#816] opened 2023-07-06 14:26 UTC
Another issue mentioned in Kathleen's feedback.

Unpublished sources that were created in OldCantus are showing on the list with the published sources. New sources that are created on NewCantus Staging, however, do not show on the list which is the expected behaviour.

Perhaps this has to do with #172

**Comment by lucasmarchd01** [comment] 2023-07-06 17:42
Update: This behaviour is expected from NewCantus since unpublished sources show up on the source list page if and only if the user is logged in as an editor

**Comment by jacobdgm** [comment] 2023-07-12 14:15
This sounds about right, @lucasmarchd01. I'm guessing that something is appearing in NewCantus that wasn't in Old, because OldCantus had both `visible` and `published` properties, and these have been combined into a single `published` property in NewCantus.

**Comment by annamorphism** [comment] 2023-07-12 16:21
yes. logged-in users will certainly be surprised to find several hundred sources that previously were private to various projects suddenly available for them to look at. I have been trying to seed the idea that this is expected behaviour, but I expect we will receive lots of comments on this.

**Comment by jacobdgm** [comment] 2023-07-13 12:42
Closing this - feel free to reopen if necessary.

**Closed as completed by jacobdgm** 2023-07-13 12:42 UTC
