### ISSUE TITLE
Modify feast entry on input form

### ISSUE THREAD

**Issue by jwang44** [DDMAL/CantusDB#51] opened 2021-05-07 17:36 UTC
Change the design, so that the indexer can 

> select an item from 1 of 4 separate pull-down lists that are connected to the `feast` field.

**Comment by jwang44** [comment] 2021-06-22 01:42
This is part of the chant input form. It will be worked on after we finish the public version of CantusDB.

**Comment by jacobdgm** [comment] 2022-09-22 15:47
This is from Debra's wishlist, correct? I don't understand what the "4 separate pull-down lists" should be.

**Comment by dchiller** [comment] 2024-11-22 21:14
@annamorphism @lucasmarchd01 I'm wondering if you have an idea of what the vision for a reworked feast entry is here? #1416 and #532 seem relevant to making feast selection easier for indexers so maybe they get at or supersede what was intended here. 

I do agree that the current entry procedure can be difficult if you don't know exactly what you're searching for (and you don't know what the Cantus Network calls the feast). I'm just not sure what is meant here to make that easier...and I'm inclined to close this issue unless we can come up with something more specific. (I could imagine having a "feast search" function on the chant create page that works similarly to the way you can search for a Cantus ID based on text, but I don't know if that's what this is)

**Comment by annamorphism** [comment] 2024-11-22 21:22
I...don't think I was looped into this conversation when it happened, and can't really visualize how four dropdowns would be involved. I'm likewise inclined to close this issue unless we have a sudden memory about it.

**Comment by dchiller** [comment] 2024-11-22 21:36
Since we have other issues already relevant to feast entry, I'm inclined to close and if we come up with more things we want after those other issues, we can come back to it. Thanks!

**Closed as completed by dchiller** 2024-11-22 21:36 UTC
Labels: enhancement, priority: low
