### ISSUE TITLE
Remember password login information

### ISSUE THREAD

**Issue by lucasmarchd01** [DDMAL/CantusDB#821] opened 2023-07-10 13:34 UTC
When logging into NewCantus, the autocomplete on the browser does not remember the password that is saved by the user. From my initial search, this looks like an issue with the browser settings/configuration rather than a problem with django, so there might not be anything we can really do about this.

Also, Debra has mentioned that she had to reset her password more than once because of invalid credentials. This could be a user error, but if other people encounter the same issue then we should look into it.

**Comment by jacobdgm** [comment] 2023-07-11 19:53
I'm going to close this - pretty sure there's nothing we can do about it on our end, and that Debra's difficulties were caused by her changing her password on staging and the browser not updating the saved password on production (or vice versa).

We can reopen this if someone else has trouble along these lines.

**Closed as completed by jacobdgm** 2023-07-11 19:53 UTC
