### ISSUE TITLE
On article detail page, add sidebar with 5 most recent news stories

### ISSUE THREAD

**Issue by jacobdgm** [DDMAL/CantusDB#444] opened 2022-12-01 16:24 UTC
On OldCantus, on every news article page, there is a sidebar listing the 5 most recent articles ([example](https://cantus.uwaterloo.ca/article/710905)). NewCantus does not currently have this sidebar ([example](http://206.12.88.113/article/32)), but probably should.

**Comment by dchiller** [comment] 2023-06-01 17:23
I was just about to create a duplicate of this...and have one addition (I don't know if this is a new or same issue):

on NewCantus, the fact that the search input field is in the same "box" as the article is odd and different than OldCantus. I think as a user I'd expect a search box in the NewCantus position to search the contents of the article, and not the entire database.

OldCantus:
<img width="1024" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/9fcb9eb8-2906-4868-8ff6-733ebe1f0d76">


NewCantus:

<img width="1129" alt="image" src="https://github.com/DDMAL/CantusDB/assets/11023634/0ec28916-ec0e-411c-b620-06f809d61ca6">

**Comment by jacobdgm** [comment] 2023-06-01 18:08
Huh - in OldCantus, when a user is logged in, this news articles sidebar isn't visible. NewCantus just uses the logged-in layout whether or not a user is logged in.

OldCantus, logged in:
![Screenshot 2023-06-01 at 2 08 21 PM](https://github.com/DDMAL/CantusDB/assets/58090591/443e620c-d958-4353-88f6-eaf38e3217fc)

We should fix this eventually, but it's still low priority.

**Closed as completed** 2023-06-26 15:46 UTC
Labels: priority: low, simple fix
