### ISSUE TITLE
Missing column/data in CSV export in `NewCantus` compared to `OldCantus`

### ISSUE THREAD

**Issue by jackyyzhang03** [DDMAL/CantusDB#694] opened 2023-06-05 19:07 UTC
I noticed that there is a column in `OldCantus` CSV export called `cao_concordances` that is not present in the CSV export of `NewCantus`.

Additionally, the `differentia_new` column is not populated in the `NewCantus` CSV export but is in `OldCantus`.

**Comment by annamorphism** [comment] 2023-06-05 19:20
I believe the CAO concordances were intentionally left unimplemented (c.f. #125 )
differentia_new should be populated, though (this is related to #693 )

**Comment by jacobdgm** [comment] 2023-06-06 14:24
Good catch, @jackyyzhang03!

The root cause of the empty `differentia_new` is deeper than just this view - I opened an issue, #701, outlining it, so I'll close this issue. I'll make a note on the front page of the repo that we've made a choice to hide the `cao_concordances` column.

**Closed as completed by jacobdgm** 2023-06-06 14:24 UTC
