### ISSUE TITLE
Paginate or scroll melody search results?

### ISSUE THREAD

**Issue by dchiller** [DDMAL/CantusDB#869] opened 2023-07-21 13:42 UTC
Melody search results currently don't seem to paginate or scroll, so you can get long, long pages. For example, try searching a two note sequence in transposition and anywhere in a melody. You'll get a very long page.

**Comment by jacobdgm** [comment] 2023-07-24 20:16
This is a good point! It's also just as it is on OldCantus. Marking this as "enhancement" etc.

**Comment by jacobdgm** [comment] 2024-03-08 16:49
duplicate of #1134 - closing.

**Closed as completed by jacobdgm** 2024-03-08 16:49 UTC
Labels: enhancement, priority: medium
